FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore C:\Users\malya\source\repos\IAmAndriiBotCmd\IAmAndriiBotCmd\IAmAndriiBotCmd.csproj

COPY . ./

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "IAmAndriiBotCmd.dll"]